### ISSUE TITLE
Notifikasi Pengingat Sholat

### ISSUE THREAD

**Issue by Andigunawan-ag** [Andigunawan-ag/prayer_reminder#3]
**Deskripsi:**
Menambahkan notifikasi pengingat untuk setiap waktu sholat.

**Checklist:**
- [ ] Mengatur waktu notifikasi berdasarkan jadwal sholat.
- [ ] Menyediakan pengaturan notifikasi (on/off).
- [ ] Menggunakan plugin

**Comment by muhamadalief153** [comment]
bang ini gimana kok gini ya gua mau ngerjain
